version: "3.8"

services:
  # Express.js app
  app:
    depends_on:
      - postgres
      - rabbitmq
      - redis
    container_name: express-app
    build: .
    # run the run.sh file
    command: sh run.sh
    ports:
      - "3000:3000"
    env_file:
      - .prod.env

  # PostgreSQL database
  postgres:
    container_name: postgres
    image: postgres:alpine3.20
    ports:
      - "5454:5432"
    environment:
      DB_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ
  rabbitmq:
    depends_on:
      - postgres
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    # redis
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  rabbitmq: {}
